##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: host_agent
        source: https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.3.1.zip
        package_name: cloudify-script-plugin
        package_version: '1.3.1'
