########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
GITHUB_USERNAME = ENV['GITHUB_USERNAME']
GITHUB_TOKEN = ENV['GITHUB_TOKEN']
PLUGIN_NAME = ENV['PLUGIN_NAME']
PLUGIN_TAG_NAME = ENV['PLUGIN_TAG_NAME']
PLUGIN_S3_FOLDER = ENV['PLUGIN_S3_FOLDER']
GITHUB_ORGANIZATION = ENV['GITHUB_ORGANIZATION']
CONSTRAINTS_FILE = ENV['CONSTRAINTS_FILE']

CENTOS_FINAL_BOX_NAME = 'chef/centos-6.5'
CENTOS7_OFFICIAL_BOX_URL = 'http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.box'


Vagrant.configure('2') do |config|
  config.vm.define "windows" do |windows|
    windows.vm.box = "dummy"
    windows.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    windows.vm.guest = :windows
    windows.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      # this a pre-baked AMI, not pure base image
      aws.ami = "ami-118ee566"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "Administrator"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant windows plugin build" }
      aws.security_groups = "vagrant_windows"
    end
    windows.vm.synced_folder ".", "/home/Administrator/packaging"
    # shell provisioning uses bash, so use cmd to run batch script
    windows.vm.provision "shell" do |shell|
      shell.path = 'provision.sh'
      shell.args = "#{GITHUB_USERNAME} #{GITHUB_TOKEN} #{AWS_ACCESS_KEY_ID} #{AWS_ACCESS_KEY} #{PLUGIN_NAME} #{PLUGIN_TAG_NAME} #{PLUGIN_S3_FOLDER} #{GITHUB_ORGANIZATION} #{CONSTRAINTS_FILE}"
      shell.privileged = false
    end
  end

end
