apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-2
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: py310
    image: python:3.10
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 1.5
        memory: 2Gi
      limits:
        cpu: 2.5
        memory: 2Gi
  - name: py36
    image: python:3.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 1.5
        memory: 2Gi
      limits:
        cpu: 2.5
        memory: 2Gi
  - name: rabbitmq374
    image: rabbitmq:3.7.4
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
