apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py27
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
        runAsUser: 0
        privileged: true
  - name: py36
    image: circleci/python:3.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rabbitmq374
    image: rabbitmq:3.7.4
  - name: py26
    image: circleci/python:2.7-stretch
    resources:
      requests:
        cpu: 3
    command:
    - cat
    tty: true
    securityContext:
        runAsUser: 0
        privileged: true
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
