apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: py26
    image: circleci/python:2.7-stretch
    command:
    - cat
    tty: true
    securityContext:
        runAsUser: 0
        privileged: true
    resources:
      requests:
        cpu: 0.4
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
  - name: py27
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
        runAsUser: 0
        privileged: true
    resources:
      requests:
        cpu: 0.4
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
  - name: py36
    image: circleci/python:3.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 0.4
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
  - name: rabbitmq374
    image: rabbitmq:3.7.4
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.1
        memory: 200Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
