apiVersion: v1
kind: Pod
metadata:
  name: cloudify-common
  labels:
    name: cloudify-common
spec:
  containers:
  - name: py26
    image: circleci/python:2.7-stretch
    #image: rabbitmq:3.7.4
    resources:
     # limits:
      #  memory: "128Mi"
     #   cpu: "500m"
    #ports:
     # - containerPort: <Port>
  - name: py27
    image: circleci/python:2.7
    #image: rabbitmq:3.7.4
  - name: py36
    image: circleci/python:3.6
    #image: rabbitmq:3.7.4
  - name: docs_builder27
    image: circleci/python:2.7
  - name: docs_builder36
    image: circleci/python:3.6
