pipeline {
  agent {
    kubernetes {
      label 'common'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/build-pod.yaml'
    }
  }

  options {
    checkoutToSubdirectory('cloudify-common')
    buildDiscarder(logRotator(numToKeepStr:'30'))
    timeout(time: 60, unit: 'MINUTES')
    timestamps()
  }

  environment {
    branch = "${env.BRANCH_NAME}"
    workspace = "${env.WORKSPACE}"
    stage_dir = "cloudify-common"
    cfy_manager_url = 'https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager'
    cfy_node_rpm = 'http://repository.cloudifysource.org/cloudify/components/nodejs-12.16.1-1nodesource.x86_64.rpm'
  }

  stages {
      stage ('flake8_py27'){
          steps{
              container('docs_builder27'){
                  /* checkout */
                  echo 'install flake 8'
                  sh "pip install flake8 --user"
                  echo 'run flake8'
                  sh "flake8 dsl_parser script_runner cloudify cloudify_rest_client"
              }
          }
      }
      stage (flake8_py36){
          steps{
              container('docs_builder36'){
                  /* checkout */
                  echo 'install flake 8'
                  sh "pip install flake8 --user"
                  echo 'run flake8'
                  sh "flake8 dsl_parser script_runner cloudify cloudify_rest_client"
              }
          }
      }

  }